#ifndef __usf_plattform_h__
#define __usf_plattform_h__
#include <Wire.h>

#define GENERAL_SERIAL_SPEED 115200
#define ENABLE_HARDWARE_AVERAGING
#define CREATE_VIRTUAL_SENSOR_IF_NOT_HARDWARE_SENSORS_FOUND


#if defined(IS_STM32F4_BOARD)
    
    #define ERROR_LED_PIN PD15
    #define STATUS_LED_PIN PD14
    #define SINGLE_MODE_PIN PC1
    #define SYNC_PIN_IRQ_INPUT PA0
    #define SYNC_PIN_STATUS_LED PD13

    #define USER_BUTTON_TRIGGER_INPUT PA0 // ON STM32F407G-DISC1
    // I2C INTERFACE TO COMMUNICATE WITH ATTACHED SENSORS
    #define SENSOR_WIRE_SCL_PIN PB6
    #define SENSOR_WIRE_SDA_PIN PB9
    #define SENSOR_WIRE Wire
    // SERIAL PORT FOR DEBUGGING
    #define DEBUG_SERIAL Serial // ON STM32F4 WITH USB SUPPORT => Serial = USB CDC SERIAL
    // SERIAL PINS FOR COMMUNICATING WITH HOST FOR ANC NUMBERING
    #define HOST_SERIAL_RX PA3
    #define HOST_SERIAL_TX PA2
    #define HOST_SERIAL Serial1

    // PERFORMS HARD RESET OF THE CHIP
    #define RESET_SYSTEM_FUNCTION() NVIC_SystemReset()

    #ifdef ENABLE_HARDWARE_AVERAGING
        #ifdef USER_BUTTON_TRIGGER_INPUT
            #define MAX_AVERAGING_COUNT 50 // SIZE FOR RING BUFFER LIMITED DUE RAM CAPACITY
        #else 
            #define MAX_AVERAGING_COUNT 100 // SIZE FOR RING BUFFER LIMITED DUE RAM CAPACITY
        #endif
        
        #define READOUT_SPEED_IN_SINGLEMODE_HZ 200
    #else
        #define READOUT_SPEED_IN_SINGLEMODE_HZ 100
    #endif

#elif defined(IS_RP2040_BOARD)
    #define ERROR_LED_PIN 25
    #define STATUS_LED_PIN 6
    #define SINGLE_MODE_PIN 13
    #define SYNC_PIN_IRQ_INPUT 8
    #define SYNC_PIN_STATUS_LED 9
    #define USER_BUTTON_TRIGGER_INPUT 15
    //#define USER_BUTTON_TRIGGER_INPUT 15
    // I2C INTERFACE TO COMMUNICATE WITH ATTACHED SENSORS
    #define SENSOR_WIRE Wire // ON RP2040 SDA4/SCL5

    // ENALE SECOND I2C PORT
    #define SENSOR_WIRE_ALT
    #define SENSOR_WIRE_ALT_SCL_PIN 3
    #define SENSOR_WIRE_ALT_SDA_PIN 2
    // SERIAL PORT FOR DEBUGGING
    #define DEBUG_SERIAL Serial // ON RP2040 WITH DEBUG PROBE PINS TX0/ RX1
    // SERIAL PINS FOR COMMUNICATING WITH HOST FOR ANC NUMBERING
    #define HOST_SERIAL Serial1 // On RP2040

    // PERFORMS HARD RESET OF THE CHIP
    #define RESET_SYSTEM_FUNCTION()

    #ifdef ENABLE_HARDWARE_AVERAGING
        #ifdef USER_BUTTON_TRIGGER_INPUT
            #define MAX_AVERAGING_COUNT 50 // SIZE FOR RING BUFFER LIMITED DUE RAM CAPACITY
        #else 
            #define MAX_AVERAGING_COUNT 100 // SIZE FOR RING BUFFER LIMITED DUE RAM CAPACITY
        #endif
        #define READOUT_SPEED_IN_SINGLEMODE_HZ 200
    #else
        #define READOUT_SPEED_IN_SINGLEMODE_HZ 100
    #endif

#endif

#endif