# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: readout.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='readout.proto',
  package='readout',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rreadout.proto\x12\x07readout\"\x8a\x01\n\x0ereadout_result\x12\x13\n\x0bsensorindex\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\x12\t\n\x01z\x18\x04 \x02(\x02\x12\t\n\x01\x62\x18\x05 \x02(\x02\x12\x11\n\treadcount\x18\x06 \x02(\x05\x12\x0c\n\x04temp\x18\x07 \x02(\x02\x12\x16\n\x0esensordistance\x18\x08 \x02(\x05\"l\n\x0csystem_state\x12\x1d\n\x05state\x18\x01 \x02(\x0e\x32\x0e.readout.state\x12(\n\x07reading\x18\x02 \x02(\x0b\x32\x17.readout.readout_result\x12\x13\n\x0buser_button\x18\x03 \x02(\x08*T\n\x05state\x12\x11\n\rstate_unknown\x10\x01\x12\x15\n\x11state_read_result\x10\x02\x12\x0e\n\nstate_wait\x10\x03\x12\x11\n\rstate_running\x10\x04')
)

_STATE = _descriptor.EnumDescriptor(
  name='state',
  full_name='readout.state',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='state_unknown', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='state_read_result', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='state_wait', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='state_running', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=277,
  serialized_end=361,
)
_sym_db.RegisterEnumDescriptor(_STATE)

state = enum_type_wrapper.EnumTypeWrapper(_STATE)
state_unknown = 1
state_read_result = 2
state_wait = 3
state_running = 4



_READOUT_RESULT = _descriptor.Descriptor(
  name='readout_result',
  full_name='readout.readout_result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorindex', full_name='readout.readout_result.sensorindex', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='readout.readout_result.x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='readout.readout_result.y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='readout.readout_result.z', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='readout.readout_result.b', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readcount', full_name='readout.readout_result.readcount', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='readout.readout_result.temp', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensordistance', full_name='readout.readout_result.sensordistance', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=165,
)


_SYSTEM_STATE = _descriptor.Descriptor(
  name='system_state',
  full_name='readout.system_state',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='readout.system_state.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reading', full_name='readout.system_state.reading', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_button', full_name='readout.system_state.user_button', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=275,
)

_SYSTEM_STATE.fields_by_name['state'].enum_type = _STATE
_SYSTEM_STATE.fields_by_name['reading'].message_type = _READOUT_RESULT
DESCRIPTOR.message_types_by_name['readout_result'] = _READOUT_RESULT
DESCRIPTOR.message_types_by_name['system_state'] = _SYSTEM_STATE
DESCRIPTOR.enum_types_by_name['state'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

readout_result = _reflection.GeneratedProtocolMessageType('readout_result', (_message.Message,), dict(
  DESCRIPTOR = _READOUT_RESULT,
  __module__ = 'readout_pb2'
  # @@protoc_insertion_point(class_scope:readout.readout_result)
  ))
_sym_db.RegisterMessage(readout_result)

system_state = _reflection.GeneratedProtocolMessageType('system_state', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEM_STATE,
  __module__ = 'readout_pb2'
  # @@protoc_insertion_point(class_scope:readout.system_state)
  ))
_sym_db.RegisterMessage(system_state)


# @@protoc_insertion_point(module_scope)
